services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: apache/kafka:latest
  #   # depends_on:
  #   #   - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: kafka_events
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  producer:
    build:
      context: ./producer
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: events_topic
    depends_on:
      - broker
    command: ["node", "index.js"]

  consumer:
    build:
      context: ./consumer
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: events_topic
      KAFKA_GROUP_ID: consumer_group_1
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: kafka_events
      MONGO_COLLECTION_NAME: events
    depends_on:
      - broker
      - mongodb
    command: ["node", "index.js"]

  api:
    build:
      context: ./api
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: kafka_events
      MONGO_COLLECTION_NAME: events
      PORT: 3000
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongo_data:
