# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: enginnvr/api:latest  # Docker Hub'dan alınacak imaj
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB_NAME
              value: "kafka_events"
            - name: MONGO_COLLECTION_NAME
              value: "events"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
