# consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: enginnvr/consumer:latest  # Docker Hub'dan alınacak imaj
          environment:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "events_topic"
            - name: KAFKA_GROUP_ID
              value: "consumer_group_1"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB_NAME
              value: "kafka_events"
            - name: MONGO_COLLECTION_NAME
              value: "events"
          command: ["node", "index.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - port: 8081
      targetPort: 8081
