apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      containers:
        - name: consumer
          image: yourrepo/consumer:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "events_topic"
            - name: KAFKA_GROUP_ID
              value: "consumer_group_1"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB_NAME
              value: "kafka_events"
            - name: MONGO_COLLECTION_NAME
              value: "events"
          ports:
            - containerPort: 8081
