apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          readinessProbe:
            httpGet:
              path: /health
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
