apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: yourrepo/producer:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "events_topic"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: producer
