# producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: enginnvr/producer:latest  # Docker Hub'dan alınacak imaj
          environment:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "events_topic"
          command: ["node", "index.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  ports:
    - port: 8080
      targetPort: 8080
