apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka-broker 9092; do echo waiting for kafka; sleep 2; done;']
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      containers:
        - name: producer
          image: yourrepo/producer:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker:9092"
            - name: KAFKA_TOPIC
              value: "events_topic"
          ports:
            - containerPort: 8080
